

NAMES = {}


NAMES['amsterdam'] = {
    '166.pb':'Kleine Wereld',
# '179.pb':'',
# '212.pb':'',
# '252.pb':'',
# '267.pb':'',
# '285.pb':'',
# '287.pb':'',
# '288.pb':'',
# '289.pb':'',
# '304.pb':'',
# '309.pb':'',
# '324.pb':'',
# '332.pb':'',
# '335.pb':'',
# '358.pb':'',
# '417.pb':'',
# '489.pb':'',
# '490.pb':'',
# '491.pb':'',
# '492.pb':'',
# '509.pb':'',
# '515.pb':'',
# '522.pb':'',
# '523.pb':'',
# '524.pb':'',
# '525.pb':'',
# '588.pb':'',
# '604.pb':'',
# '605.pb':'',
# '613.pb':'',
# '619.pb':'',
# '621.pb':'',
# '622.pb':'',
# '628.pb':'',
# '631.pb':'',
# '643.pb':'',
# '644.pb':'',
# '645.pb':'',
# '646.pb':'',
# '647.pb':'',
}

NAMES['poznan_2023'] = {
    # 'poland_poznan_2023.pb' : '',
    # 'poland_poznan_2023_I.pb': '',
    # 'poland_poznan_2023_II.pb': '',
    # 'poland_poznan_2023_III.pb': '',
    # 'poland_poznan_2023_IV.pb': '',
    # 'poland_poznan_2023_IX.pb' : '',
    # 'poland_poznan_2023_V.pb' : '',
    # 'poland_poznan_2023_VI.pb' : '',
    # 'poland_poznan_2023_VII.pb' : '',
    # 'poland_poznan_2023_VIII.pb' : '',
    # 'poland_poznan_2023_X.pb' : '',
    # 'poland_poznan_2023_XI.pb' : '',
    # 'poland_poznan_2023_XII.pb' : '',
    # 'poland_poznan_2023_XIII.pb' : '',
    # 'poland_poznan_2023_ZB.pb' : '',
}

# WARSZAWA
NAMES['warszawa_2023'] = {
    # 'poland_warszawa_2023_bemowo.pb': 'Bemowo',
    # 'poland_warszawa_2023_bialoleka.pb': 'Bialoleka',
    # 'poland_warszawa_2023_bielany.pb': 'Bielany',
    # 'poland_warszawa_2023_mokotow.pb': 'Mokotow',
    # 'poland_warszawa_2023_ochota.pb': 'Ochota',
    # 'poland_warszawa_2023_praga-polnoc.pb': 'Praga-Polnoc',
    # 'poland_warszawa_2023_praga-poludnie.pb': 'Praga-Poludnie',
    # 'poland_warszawa_2023_rembertow.pb': 'Rembertow',
    # 'poland_warszawa_2023_srodmiescie.pb': 'Srodmiescie',
    # 'poland_warszawa_2023_targowek.pb': 'Targowek',
    # 'poland_warszawa_2023_ursus.pb': 'Ursus',
    # 'poland_warszawa_2023_ursynow.pb': 'Ursynow',
    'poland_warszawa_2023_wawer.pb': 'Wawer',
    # 'poland_warszawa_2023_wesola.pb': 'Wesola',
    # 'poland_warszawa_2023_wilanow.pb': 'Wilanow',
    # 'poland_warszawa_2023_wlochy.pb': 'Wlochy',
    # 'poland_warszawa_2023_wola.pb': 'Wola',
    # 'poland_warszawa_2023_zoliborz.pb': 'Zoliborz',
}


NAMES['warszawa_2022'] = {
    'poland_warszawa_2022_bemowo.pb': 'Bemowo',
    'poland_warszawa_2022_bialoleka.pb': 'Bialoleka',
    'poland_warszawa_2022_bielany.pb': 'Bielany',
    'poland_warszawa_2022_mokotow.pb': 'Mokotow',
    'poland_warszawa_2022_ochota.pb': 'Ochota',
    'poland_warszawa_2022_praga-polnoc.pb': 'Praga-Polnoc',
    'poland_warszawa_2022_praga-poludnie.pb': 'Praga-Poludnie',
    'poland_warszawa_2022_rembertow.pb': 'Rembertow',
    'poland_warszawa_2022_srodmiescie.pb': 'Srodmiescie',
    'poland_warszawa_2022_targowek.pb': 'Targowek',
    'poland_warszawa_2022_ursus.pb': 'Ursus',
    'poland_warszawa_2022_ursynow.pb': 'Ursynow',
    'poland_warszawa_2022_wawer.pb': 'Wawer',
    'poland_warszawa_2022_wesola.pb': 'Wesola',
    'poland_warszawa_2022_wilanow.pb': 'Wilanow',
    'poland_warszawa_2022_wlochy.pb': 'Wlochy',
    'poland_warszawa_2022_wola.pb': 'Wola',
    'poland_warszawa_2022_zoliborz.pb': 'Zoliborz',
}

NAMES['warszawa_2021'] = {
    'poland_warszawa_2021_bemowo.pb': 'Bemowo',
    'poland_warszawa_2021_bialoleka.pb': 'Bialoleka',
    'poland_warszawa_2021_bielany.pb': 'Bielany',
    'poland_warszawa_2021_mokotow.pb': 'Mokotow',
    'poland_warszawa_2021_ochota.pb': 'Ochota',
    'poland_warszawa_2021_praga-polnoc.pb': 'Praga-Polnoc',
    'poland_warszawa_2021_praga-poludnie.pb': 'Praga-Poludnie',
    'poland_warszawa_2021_rembertow.pb': 'Rembertow',
    'poland_warszawa_2021_srodmiescie.pb': 'Srodmiescie',
    'poland_warszawa_2021_targowek.pb': 'Targowek',
    'poland_warszawa_2021_ursus.pb': 'Ursus',
    'poland_warszawa_2021_ursynow.pb': 'Ursynow',
    'poland_warszawa_2021_wawer.pb': 'Wawer',
    'poland_warszawa_2021_wesola.pb': 'Wesola',
    'poland_warszawa_2021_wilanow.pb': 'Wilanow',
    'poland_warszawa_2021_wlochy.pb': 'Wlochy',
    'poland_warszawa_2021_wola.pb': 'Wola',
    'poland_warszawa_2021_zoliborz.pb': 'Zoliborz',
}

NAMES['warszawa_2020'] = {
    'poland_warszawa_2020_bemowo.pb': 'Bemowo',
    'poland_warszawa_2020_bialoleka.pb': 'Bialoleka',
    'poland_warszawa_2020_bielany.pb': 'Bielany',
    'poland_warszawa_2020_mokotow.pb': 'Mokotów',
    'poland_warszawa_2020_ochota.pb': 'Ochota',
    'poland_warszawa_2020_praga-polnoc.pb': 'Praga-Polnoc',
    'poland_warszawa_2020_praga-poludnie.pb': 'Praga-Poludnie',
    'poland_warszawa_2020_rembertow.pb': 'Rembertow',
    'poland_warszawa_2020_srodmiescie.pb': 'Srodmiescie',
    'poland_warszawa_2020_targowek.pb': 'Targowek',
    'poland_warszawa_2020_ursus.pb': 'Ursus',
    'poland_warszawa_2020_ursynow.pb': 'Ursynow',
    'poland_warszawa_2020_wawer.pb': 'Wawer',
    'poland_warszawa_2020_wesola.pb': 'Wesola',
    'poland_warszawa_2020_wilanow.pb': 'Wilanow',
    'poland_warszawa_2020_wlochy.pb': 'Wlochy',
    'poland_warszawa_2020_wola.pb': 'Wola',
    'poland_warszawa_2020_zoliborz.pb': 'Zoliborz',
}

# KRAKOW
NAMES['krakow_2022'] = {
    'poland_krakow_2022_bienczyce.pb': 'Bienczyce',
    'poland_krakow_2022_biezanow-prokocim.pb': 'Biezanow-Prokocim',
    'poland_krakow_2022_bronowice.pb': 'Bronowice',
    'poland_krakow_2022_czyzyny.pb': 'Czyzyny',
    'poland_krakow_2022_debniki.pb': 'Debniki',
    'poland_krakow_2022_grzegorzki.pb': 'Grzegorzki',
    'poland_krakow_2022_krowodrza.pb': 'Krowodrza',
    'poland_krakow_2022_lagiewniki-borek-falecki.pb': 'Lagiewniki-Borek-Falecki',
    'poland_krakow_2022_mistrzejowice.pb': 'Mistrzejowice',
    'poland_krakow_2022_nowa-huta.pb': 'Nowa-Huta',
    'poland_krakow_2022_podgorze.pb': 'Podgorze',
    'poland_krakow_2022_podgorze-duchackie.pb': 'Podgorze-Duchackie',
    'poland_krakow_2022_pradnik-bialy.pb': 'Pradnik-Bialy',
    'poland_krakow_2022_pradnik-czerwony.pb': 'Pradnik-Czerwony',
    'poland_krakow_2022_stare-miasto.pb': 'Stare-Miasto',
    'poland_krakow_2022_swoszowice.pb': 'Swoszowice',
    'poland_krakow_2022_wzgorza-krzeslawickie.pb': 'Wzgorza-Krzeslawickie',
    'poland_krakow_2022_zwierzyniec.pb': 'Zwierzyniec',
}

NAMES['krakow_2021'] = {
    'poland_krakow_2021_bienczyce.pb': 'Bienczyce',
    'poland_krakow_2021_biezanow-prokocim.pb': 'Biezanow-Prokocim',
    'poland_krakow_2021_bronowice.pb': 'Bronowice',
    'poland_krakow_2021_czyzyny.pb': 'Czyzyny',
    'poland_krakow_2021_debniki.pb': 'Debniki',
    'poland_krakow_2021_grzegorzki.pb': 'Grzegorzki',
    'poland_krakow_2021_krowodrza.pb': 'Krowodrza',
    'poland_krakow_2021_lagiewniki-borek-falecki.pb': 'Lagiewniki-Borek-Falecki',
    'poland_krakow_2021_mistrzejowice.pb': 'Mistrzejowice',
    'poland_krakow_2021_nowa-huta.pb': 'Nowa-Huta',
    'poland_krakow_2021_podgorze.pb': 'Podgorze',
    'poland_krakow_2021_podgorze-duchackie.pb': 'Podgorze-Duchackie',
    'poland_krakow_2021_pradnik-bialy.pb': 'Pradnik-Bialy',
    'poland_krakow_2021_pradnik-czerwony.pb': 'Pradnik-Czerwony',
    'poland_krakow_2021_stare-miasto.pb': 'Stare-Miasto',
    'poland_krakow_2021_swoszowice.pb': 'Swoszowice',
    'poland_krakow_2021_wzgorza-krzeslawickie.pb': 'Wzgorza-Krzeslawickie',
    'poland_krakow_2021_zwierzyniec.pb': 'Zwierzyniec',
}

NAMES['krakow_2020'] = {
    'poland_krakow_2020_bienczyce.pb': 'Bienczyce',
    'poland_krakow_2020_biezanow-prokocim.pb': 'Biezanow-Prokocim',
    'poland_krakow_2020_bronowice.pb': 'Bronowice',
    'poland_krakow_2020_czyzyny.pb': 'Czyzyny',
    'poland_krakow_2020_debniki.pb': 'Debniki',
    'poland_krakow_2020_grzegorzki.pb': 'Grzegorzki',
    'poland_krakow_2020_krowodrza.pb': 'Krowodrza',
    'poland_krakow_2020_lagiewniki-borek-falecki.pb': 'Lagiewniki-Borek-Falecki',
    'poland_krakow_2020_mistrzejowice.pb': 'Mistrzejowice',
    'poland_krakow_2020_nowa-huta.pb': 'Nowa-Huta',
    'poland_krakow_2020_podgorze.pb': 'Podgorze',
    'poland_krakow_2020_podgorze-duchackie.pb': 'Podgorze-Duchackie',
    'poland_krakow_2020_pradnik-bialy.pb': 'Pradnik-Bialy',
    'poland_krakow_2020_pradnik-czerwony.pb': 'Pradnik-Czerwony',
    'poland_krakow_2020_stare-miasto.pb': 'Stare-Miasto',
    'poland_krakow_2020_swoszowice.pb': 'Swoszowice',
    'poland_krakow_2020_wzgorza-krzeslawickie.pb': 'Wzgorza-Krzeslawickie',
    'poland_krakow_2020_zwierzyniec.pb': 'Zwierzyniec',
}

# ZABRZE
NAMES['zabrze_2021'] = {
    'poland_zabrze_2021_biskupice.pb': '',
    'poland_zabrze_2021_centrum-polnoc.pb': '',
    'poland_zabrze_2021_centrum-poludnie.pb': '',
    'poland_zabrze_2021_grzybowice.pb': '',
    'poland_zabrze_2021_guido.pb': '',
    'poland_zabrze_2021_helenka.pb': '',
    'poland_zabrze_2021_konczyce.pb': '',
    'poland_zabrze_2021_maciejow.pb': '',
    'poland_zabrze_2021_makoszowy.pb': '',
    'poland_zabrze_2021_mikulczyce.pb': '',
    'poland_zabrze_2021_osiedle-mikolaja-kopernika.pb': '',
    'poland_zabrze_2021_osiedle-mlodego-gornika.pb': '',
    'poland_zabrze_2021_osiedle-tadeusza-kotarbinskiego.pb': '',
    'poland_zabrze_2021_pawlow.pb': '',
    'poland_zabrze_2021_rokitnica.pb': '',
    'poland_zabrze_2021_zaborze-polnoc.pb': '',
    'poland_zabrze_2021_zaborze-poludnie.pb': '',
    'poland_zabrze_2021_zandka.pb': '',
}

NAMES['zabrze_2020'] = {
    # 'poland_zabrze_2020_biskupice.pb': '',
    # 'poland_zabrze_2020_centrum-polnoc.pb': '',
    # 'poland_zabrze_2020_centrum-poludnie.pb': '',
    # 'poland_zabrze_2020_grzybowice.pb': '',
    'poland_zabrze_2020_guido.pb': '',
    'poland_zabrze_2020_helenka.pb': '',
    'poland_zabrze_2020_konczyce.pb': '',
    'poland_zabrze_2020_maciejow.pb': '',
    'poland_zabrze_2020_makoszowy.pb': '',
    'poland_zabrze_2020_mikulczyce.pb': '',
    'poland_zabrze_2020_osiedle-mikolaja-kopernika.pb': '',
    'poland_zabrze_2020_osiedle-mlodego-gornika.pb': '',
    'poland_zabrze_2020_osiedle-tadeusza-kotarbinskiego.pb': '',
    'poland_zabrze_2020_pawlow.pb': '',
    'poland_zabrze_2020_rokitnica.pb': '',
    'poland_zabrze_2020_zaborze-polnoc.pb': '',
    'poland_zabrze_2020_zaborze-poludnie.pb': '',
    'poland_zabrze_2020_zandka.pb': '',
}

# KATOWICE
NAMES['katowice_2021'] = {
    'poland_katowice_2021_bogucice.pb': '',
    'poland_katowice_2021_brynow-czesc-wschodnia-osiedle-zgrzebnioka.pb': '',
    'poland_katowice_2021_dab.pb': '',
    'poland_katowice_2021_dabrowka-mala.pb': '',
    'poland_katowice_2021_giszowiec.pb': '',
    'poland_katowice_2021_janow-nikiszowiec.pb': '',
    'poland_katowice_2021_kostuchna.pb': '',
    'poland_katowice_2021_koszutka.pb': '',
    'poland_katowice_2021_ligota-panewniki.pb': '',
    'poland_katowice_2021_murcki.pb': '',
    'poland_katowice_2021_osiedle-paderewskiego-muchowiec.pb': '',
    'poland_katowice_2021_osiedle-tysiaclecia.pb': '',
    'poland_katowice_2021_osiedle-witosa.pb': '',
    'poland_katowice_2021_piotrowice-ochojec.pb': '',
    'poland_katowice_2021_podlesie.pb': '',
    'poland_katowice_2021_srodmiescie.pb': '',
    'poland_katowice_2021_szopienice-burowiec.pb': '',
    'poland_katowice_2021_welnowiec-jozefowiec.pb': '',
    'poland_katowice_2021_zaleska-halda-brynow-czesc-zachodnia.pb': '',
    'poland_katowice_2021_zaleze.pb': '',
    'poland_katowice_2021_zarzecze.pb': '',
    'poland_katowice_2021_zawodzie.pb': '',
}

NAMES['katowice_2020'] = {
    'poland_katowice_2020_bogucice.pb': '',
    'poland_katowice_2020_brynow-czesc-wschodnia-osiedle-zgrzebnioka.pb': '',
    'poland_katowice_2020_dab.pb': '',
    'poland_katowice_2020_dabrowka-mala.pb': '',
    'poland_katowice_2020_giszowiec.pb': '',
    'poland_katowice_2020_janow-nikiszowiec.pb': '',
    'poland_katowice_2020_kostuchna.pb': '',
    'poland_katowice_2020_koszutka.pb': '',
    'poland_katowice_2020_ligota-panewniki.pb': '',
    'poland_katowice_2020_murcki.pb': '',
    'poland_katowice_2020_osiedle-paderewskiego-muchowiec.pb': '',
    'poland_katowice_2020_osiedle-tysiaclecia.pb': '',
    'poland_katowice_2020_osiedle-witosa.pb': '',
    'poland_katowice_2020_piotrowice-ochojec.pb': '',
    'poland_katowice_2020_podlesie.pb': '',
    'poland_katowice_2020_srodmiescie.pb': '',
    'poland_katowice_2020_szopienice-burowiec.pb': '',
    'poland_katowice_2020_welnowiec-jozefowiec.pb': '',
    'poland_katowice_2020_zaleska-halda-brynow-czesc-zachodnia.pb': '',
    'poland_katowice_2020_zaleze.pb': '',
    'poland_katowice_2020_zarzecze.pb': '',
    'poland_katowice_2020_zawodzie.pb': '',
}

# GDANSK
NAMES['gdansk_2020'] = {
    'poland_gdansk_2020_aniolki.pb': '',
    'poland_gdansk_2020_bretowo.pb': '',
    'poland_gdansk_2020_brzezno.pb': '',
    'poland_gdansk_2020_chelm.pb': '',
    'poland_gdansk_2020_jasien.pb': '',
    'poland_gdansk_2020_kokoszki.pb': '',
    'poland_gdansk_2020_krakowiec-gorki-zachodnie.pb': '',
    'poland_gdansk_2020_letnica.pb': '',
    'poland_gdansk_2020_matarnia.pb': '',
    'poland_gdansk_2020_mlyniska.pb': '',
    'poland_gdansk_2020_nowy-port.pb': '',
    'poland_gdansk_2020_oliwa.pb': '',
    'poland_gdansk_2020_olszynka.pb': '',
    'poland_gdansk_2020_orunia-gorna-gdansk-poludnie.pb': '',
    'poland_gdansk_2020_orunia-sw-wojciech-lipce.pb': '',
    'poland_gdansk_2020_osowa.pb': '',
    'poland_gdansk_2020_piecki-migowo.pb': '',
    'poland_gdansk_2020_przerobka.pb': '',
    'poland_gdansk_2020_przymorze-male.pb': '',
    'poland_gdansk_2020_przymorze-wielkie.pb': '',
    'poland_gdansk_2020_rudniki.pb': '',
    'poland_gdansk_2020_siedlce.pb': '',
    'poland_gdansk_2020_srodmiescie.pb': '',
    'poland_gdansk_2020_stogi.pb': '',
    'poland_gdansk_2020_strzyza.pb': '',
    'poland_gdansk_2020_suchanino.pb': '',
    'poland_gdansk_2020_ujescisko-lostowice.pb': '',
    'poland_gdansk_2020_vii-dwor.pb': '',
    'poland_gdansk_2020_wrzeszcz-dolny.pb': '',
    'poland_gdansk_2020_wrzeszcz-gorny.pb': '',
    'poland_gdansk_2020_wyspa-sobieszewska.pb': '',
    'poland_gdansk_2020_wzgorze-mickiewicza.pb': '',
    'poland_gdansk_2020_zabianka-wejhera-jelitkowo-tysiaclecia.pb': '',
    'poland_gdansk_2020_zaspa-mlyniec.pb': '',
    'poland_gdansk_2020_zaspa-rozstaje.pb': '',
}

# CZESTOCHOWA
NAMES['czestochowa_2020'] = {
    'poland_czestochowa_2020_bleszno.pb': '',
    'poland_czestochowa_2020_czestochowka-parkitka.pb': '',
    'poland_czestochowa_2020_dzbow.pb': '',
    'poland_czestochowa_2020_gnaszyn-kawodrza.pb': '',
    'poland_czestochowa_2020_grabowka.pb': '',
    'poland_czestochowa_2020_kiedrzyn.pb': '',
    'poland_czestochowa_2020_lisiniec.pb': '',
    'poland_czestochowa_2020_mirow.pb': '',
    'poland_czestochowa_2020_ostatni-grosz.pb': '',
    'poland_czestochowa_2020_podjasnogorska.pb': '',
    'poland_czestochowa_2020_polnoc.pb': '',
    'poland_czestochowa_2020_rakow.pb': '',
    'poland_czestochowa_2020_srodmiescie.pb': '',
    'poland_czestochowa_2020_stare-miasto.pb': '',
    'poland_czestochowa_2020_stradom.pb': '',
    'poland_czestochowa_2020_trzech-wieszczow.pb': '',
    'poland_czestochowa_2020_tysiaclecie.pb': '',
    'poland_czestochowa_2020_wrzosowiak.pb': '',
    'poland_czestochowa_2020_wyczerpy-aniolow.pb': '',
    'poland_czestochowa_2020_zawodzie-dabie.pb': '',
}

# LODZ
NAMES['lodz_2020'] = {
    'poland_lodz_2020_andrzejow.pb': '',
    'poland_lodz_2020_baluty-centrum.pb': '',
    'poland_lodz_2020_baluty-doly.pb': '',
    'poland_lodz_2020_baluty-zachodnie.pb': '',
    'poland_lodz_2020_chojny.pb': '',
    'poland_lodz_2020_chojny-dabrowa.pb': '',
    'poland_lodz_2020_dolina-lodki.pb': '',
    'poland_lodz_2020_gorniak.pb': '',
    'poland_lodz_2020_im-montwilla-mireckiego.pb': '',
    'poland_lodz_2020_julianow-marysin-rogi.pb': '',
    'poland_lodz_2020_karolew-retkinia-wschod.pb': '',
    'poland_lodz_2020_koziny.pb': '',
    'poland_lodz_2020_lagiewniki.pb': '',
    'poland_lodz_2020_lublinek-pienista.pb': '',
    'poland_lodz_2020_mileszki.pb': '',
    'poland_lodz_2020_nad-nerem.pb': '',
    'poland_lodz_2020_nowosolna.pb': '',
    'poland_lodz_2020_nr-33.pb': '',
    'poland_lodz_2020_olechow-janow.pb': '',
    'poland_lodz_2020_piastow-kurak.pb': '',
    'poland_lodz_2020_radogoszcz.pb': '',
    'poland_lodz_2020_retkinia-zachod-smulsko.pb': '',
    'poland_lodz_2020_rokicie.pb': '',
    'poland_lodz_2020_ruda.pb': '',
    'poland_lodz_2020_srodmiescie-katedralna.pb': '',
    'poland_lodz_2020_srodmiescie-wschod.pb': '',
    'poland_lodz_2020_stare-polesie.pb': '',
    'poland_lodz_2020_stary-widzew.pb': '',
    'poland_lodz_2020_stoki-sikawa-podgorze.pb': '',
    'poland_lodz_2020_teofilow-wielkopolska.pb': '',
    'poland_lodz_2020_widzew-wschod.pb': '',
    'poland_lodz_2020_wiskitno.pb': '',
    'poland_lodz_2020_wzniesien-lodzkich.pb': '',
    'poland_lodz_2020_zarzew.pb': '',
    'poland_lodz_2020_zdrowie-mania.pb': '',
    'poland_lodz_2020_zlotno.pb': '',
}

# WROCLAW
NAMES['wroclaw_2021'] = {
    'poland_wroclaw_2021_.pb': 'a',
    'poland_wroclaw_2021_local.pb': 'b',
}

NAMES['wroclaw_2020'] = {
    'poland_wroclaw_2020_.pb': 'a',
    'poland_wroclaw_2020_local.pb': 'b',
}

NAMES['wroclaw_2019'] = {
    'poland_wroclaw_2019_.pb': 'a',
    'poland_wroclaw_2019_local.pb': 'b',
}

NAMES['snochaczewo'] = {
    'snochaczewo_1.pb': 's1'
}

NAMES['wieliczka_2023'] = {
    'poland_wieliczka_2023_green-budget.pb': 'Wieliczka'
}

NAMES['lublin_2020'] = {
    'poland_lublin_2020_.pb': ''
}

